version: '3'
services:
  mage:
    image: mageai/mageai:latest
    container_name: data-task
    command: mage start ${PROJECT_NAME}
    env_file:
      - .env
    environment:
      ENV: ${ENV}
      PG_HOST_PORT: ${PG_HOST_PORT}
      PG_HOST: ${PG_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_SCHEMA: ${POSTGRES_SCHEMA}
      POSTGRES_USER: ${POSTGRES_USER}
      PROJECT_NAME: ${PROJECT_NAME}
    ports:
      - 6789:6789
    volumes:
      - .:/home/src/
    restart: on-failure:5

  python-container:
    image: python:latest
    env_file:
      - .env
    environment:
      - DS_PATH = ${DS_PATH}
    restart: on-failure:5