name: 'covid_data'

config-version: 2
version: '1.0.0'

profile: 'covid_data'

model-paths: ["models"]
seed-paths: ["seeds"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

vars:
  env: prod

models:
  demo:
    materialized: view