covid_data:
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('PG_HOST') }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: 5432
      database: postgres # or database instead of dbname
      schema: "{{ env_var('POSTGRES_SCHEMA') }}"
      threads: 100
    duckdb:
      type: duckdb
  target: dev